"""PROV-JSON and bare JSON-LD emission tests for gnosislab_export.

Both formats are thin emitters over the same Snapshot and share the
same payload/ layout as the crate — these tests check the metadata
documents' shape against the minimal fixture store.
"""

import json
import sqlite3
import sys
import zipfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from gnosislab_export.common.snapshot import load_snapshot  # noqa: E402
from gnosislab_export.jsonld.exporter import export_jsonld  # noqa: E402
from gnosislab_export.prov.exporter import export_prov  # noqa: E402
from gnosislab_export.ro_crate.exporter import export_rocrate  # noqa: E402
from gnosislab_export.cli import main as export_cli  # noqa: E402
from export_fixtures import seed_stores  # noqa: E402


@pytest.fixture
def stores(tmp_path):
    return seed_stores(tmp_path)


# ---------------------------------------------------------------- jsonld


def test_jsonld_structure(stores, tmp_path):
    epi, ana = stores
    snap = load_snapshot(epi, ana, programme_id="prog-t1")
    out = export_jsonld(snap, tmp_path / "jsonld")

    doc = json.loads((out / "export.jsonld").read_text())
    assert doc["@context"][0] == "https://schema.org"
    graph = {e["@id"]: e for e in doc["@graph"]}

    # crate-specific nodes are dropped; provenance nodes remain
    assert "ro-crate-metadata.json" not in graph
    assert "./" not in graph
    assert graph["#trial/trl-t1"]["@type"] == "CreateAction"
    # claim isBasedOn resolves to the trial's results payload, which the
    # jsonld export also writes — the ref resolves in both formats
    assert graph["#claim/clm-t1"]["isBasedOn"] == {
        "@id": "payload/results/trl-t1.json"
    }
    assert "#conclusion/cnc-t1" in graph
    assert "#gnosislab" in graph

    # same payload layout as the crate
    code_ids = [i for i in graph if i.startswith("payload/code/")]
    assert code_ids and (out / code_ids[0]).read_text() == "x=1"
    assert (out / "payload/results/trl-t1.json").exists()
    manifest = json.loads((out / "payload/MANIFEST.json").read_text())
    assert manifest["counts"]["trials"] == 1


def test_jsonld_zip(stores, tmp_path):
    epi, ana = stores
    snap = load_snapshot(epi, ana, programme_id="prog-t1")
    zpath = export_jsonld(snap, tmp_path / "jsonld.zip", zip_it=True)
    names = zipfile.ZipFile(zpath).namelist()
    assert "export.jsonld" in names
    assert any(n.startswith("payload/code/") for n in names)


# ---------------------------------------------------------------- prov


def test_prov_structure(stores, tmp_path):
    epi, ana = stores
    snap = load_snapshot(epi, ana, programme_id="prog-t1")
    out = export_prov(snap, tmp_path / "prov")

    doc = json.loads((out / "prov.json").read_text())
    assert doc["prefix"]["prov"] == "http://www.w3.org/ns/prov#"

    # agent + trial activity with recorded start/end
    agent = doc["agent"]["gl:agent/gnosislab"]
    assert agent["prov:type"]["$"] == "prov:SoftwareAgent"
    trial = doc["activity"]["gl:trial/trl-t1"]
    assert trial["prov:type"]["$"] == "gl:Trial"
    assert trial["prov:startTime"]["$"] == "2026-10-01T00:03:00Z"
    assert trial["prov:endTime"]["$"] == "2026-10-01T00:03:12Z"

    # entities carry their roles
    assert doc["entity"]["gl:hypothesis/hyp-t1"]["prov:type"][1]["$"] == (
        "prov:Plan"
    )
    assert doc["entity"]["gl:claim/clm-t1"]["gl:confidence"] == 0.9
    assert doc["entity"]["gl:verdict/cnc-t1"]["prov:type"]["$"] == (
        "gl:Verdict"
    )

    def relvals(key, prop):
        return [v[prop] for v in doc[key].values() if prop in v]

    # observation + artifact generated by the trial; verdict by conclusion
    gen = relvals("wasGeneratedBy", "prov:entity")
    assert "gl:observation/obs-t1" in gen
    assert "gl:artifact/ffff" in gen
    assert "gl:verdict/cnc-t1" in gen

    # trial used hypothesis + code; conclusion used the evidence entity
    used = relvals("used", "prov:entity")
    assert "gl:hypothesis/hyp-t1" in used
    assert "gl:code/aabbcc" in used
    assert "gl:trial/trl-t1" in used

    # claim edge → wasDerivedFrom claim → trial
    drv = list(doc["wasDerivedFrom"].values())
    assert {
        "prov:generatedEntity": "gl:claim/clm-t1",
        "prov:usedEntity": "gl:trial/trl-t1",
        "prov:hadRole": {"$": "gl:derived_from", "type": "prov:QUALIFIED_NAME"},
    } in drv

    # agent associated with both activities
    assoc = relvals("wasAssociatedWith", "prov:activity")
    assert "gl:trial/trl-t1" in assoc
    assert "gl:conclusion/cnc-t1" in assoc

    # programme collects its hypothesis
    members = doc["hadMember"]["gl:members/prog-t1"]["prov:entity"]
    assert members == "gl:hypothesis/hyp-t1"

    # payload + manifest still emitted
    assert (out / "payload/MANIFEST.json").exists()
    assert (out / "payload/results/trl-t1.json").exists()


def test_prov_external_ref_visible(stores, tmp_path):
    epi, ana = stores
    conn = sqlite3.connect(ana)
    conn.execute(
        "INSERT INTO claim_edges VALUES "
        "('edg-x','clm-t1','ext-9','evidence','supports','src',"
        "'2026-10-01T00:05:02Z')"
    )
    conn.commit()
    conn.close()
    snap = load_snapshot(epi, ana, programme_id="prog-t1")
    doc = json.loads(
        (export_prov(snap, tmp_path / "prov") / "prov.json").read_text()
    )
    ext = doc["entity"]["gl:external/ext-9"]
    assert ext["prov:type"]["$"] == "gl:ExternalRef"
    # 'supports' is influence, not derivation
    inf = list(doc["wasInfluencedBy"].values())
    assert inf[0]["prov:influencer"] == "gl:external/ext-9"


def test_prov_zip(stores, tmp_path):
    epi, ana = stores
    snap = load_snapshot(epi, ana, programme_id="prog-t1")
    zpath = export_prov(snap, tmp_path / "prov.zip", zip_it=True)
    names = zipfile.ZipFile(zpath).namelist()
    assert "prov.json" in names


def test_rocrate_descriptor_license_cc0(stores, tmp_path):
    epi, ana = stores
    snap = load_snapshot(epi, ana, programme_id="prog-t1")
    crate = export_rocrate(snap, tmp_path / "crate")
    graph = {
        e["@id"]: e
        for e in json.loads(
            (crate / "ro-crate-metadata.json").read_text()
        )["@graph"]
    }
    # descriptor is always CC0; the dataset's license is a spec MUST,
    # so an undeclared license is a named contextual entity, not omitted
    desc = graph["ro-crate-metadata.json"]
    assert desc["license"] == {"@id": "https://spdx.org/licenses/CC0-1.0"}
    assert graph["./"]["license"] == {"@id": "#license"}
    assert graph["#license"]["name"] == "No license declared"

    crate2 = export_rocrate(
        snap, tmp_path / "crate2", license_uri="https://spdx.org/licenses/CC-BY-4.0"
    )
    graph2 = {
        e["@id"]: e
        for e in json.loads(
            (crate2 / "ro-crate-metadata.json").read_text()
        )["@graph"]
    }
    assert graph2["./"]["license"] == {
        "@id": "https://spdx.org/licenses/CC-BY-4.0"
    }


def test_cli_license_rejected_for_other_formats(stores, tmp_path):
    epi, ana = stores
    rc = export_cli(
        [
            "--programme", "prog-t1",
            "--format", "prov",
            "--license", "https://spdx.org/licenses/CC-BY-4.0",
            "--out", str(tmp_path / "prov"),
            "--episteme-db", str(epi),
            "--anamnesis-db", str(ana),
        ]
    )
    assert rc == 2


# ---------------------------------------------------------------- cli


def test_cli_dispatch_all_formats(stores, tmp_path):
    epi, ana = stores
    for fmt, doc_name in (
        ("ro-crate", "ro-crate-metadata.json"),
        ("prov", "prov.json"),
        ("jsonld", "export.jsonld"),
    ):
        out = tmp_path / fmt
        rc = export_cli(
            [
                "--programme", "prog-t1",
                "--format", fmt,
                "--out", str(out),
                "--episteme-db", str(epi),
                "--anamnesis-db", str(ana),
            ]
        )
        assert rc == 0, fmt
        assert (out / doc_name).exists()
        assert (out / "payload/MANIFEST.json").exists()
