"""gnosislab — lifecycle for the ml-* loop stack (single implementation).

This is the only implementation of the lifecycle commands — the
repo-local `gnosislab` bash script is a thin shim that execs this
CLI. Servers run detached with stdout appended to
~/.ml-<name>/logs/server.log and a pidfile at
~/.ml-<name>/run/labloop.pid (the on-disk identifiers keep the
labloop name until the subsystem is renamed).

Port resolution order:

    built-in defaults
    < ~/.config/gnosislab/ports.env   (same KEY=VALUE format as the
                                       repo's ports.env; may also set
                                       ML_EPISTEME_INGEST_TOKEN etc.)
    < environment variables           (ML_<NAME>_PORT, ML_*_GUI_URL…)

Every resolved ML_* variable is exported into each spawned server —
peer adaptors read siblings' ports/URLs from the environment, same
as `set -a; source ports.env` in the launchers.
"""

from __future__ import annotations

import os
import signal
import subprocess
import sys
import time
import urllib.request
import json
from pathlib import Path

# Start order: upstreams first, the status hub last (it reads them
# all). Stop order is the reverse — agora dies first.
COMPONENTS = ["anamnesis", "episteme", "zetesis", "arete", "agora"]

DEFAULT_PORTS = {
    "agora": 38050,
    "arete": 38060,
    "zetesis": 38070,
    "episteme": 38080,
    "anamnesis": 38090,
}

USER_CONFIG = Path.home() / ".config" / "gnosislab" / "ports.env"

# Peer wiring: each server's [adaptors.*] channels → the peer they
# read from. Mirrors the repo's ml-*.toml files — used to generate
# ~/.ml-<name>/config.toml when no config file is discoverable
# (pip installs have no repo tomls in cwd).
PEER_CHANNELS: dict[str, dict[str, str]] = {
    "episteme": {"claims": "anamnesis"},
    "zetesis": {"evidence": "episteme", "promotion": "episteme",
                "claims": "anamnesis"},
    "arete": {"loop0": "episteme", "loop1": "zetesis",
              "loop1_orchestration": "zetesis", "claims": "anamnesis"},
    "agora": {"claims": "anamnesis", "loop0": "episteme",
              "loop1": "zetesis", "loop2": "arete"},
}


def _server_config_source(name: str) -> Path | None:
    """The config file the server would find, if any — same search
    order as the servers: ./ml-<name>.toml then ~/.ml-<name>/config.toml."""
    for p in (Path.cwd() / f"ml-{name}.toml",
              _home(name) / "config.toml"):
        if p.is_file():
            return p
    return None


def _ensure_server_config(name: str) -> None:
    """Write ~/.ml-<name>/config.toml with adaptor wiring when the
    server would otherwise start unconfigured (pip installs)."""
    channels = PEER_CHANNELS.get(name)
    if not channels or _server_config_source(name) is not None:
        return
    conf = _home(name) / "config.toml"
    lines = [
        "# generated by gnosislab — edit in place or delete to",
        "# regenerate; derived from the resolved ports.",
        "[adaptors]",
        "reconnect_seconds = 15",
        "call_timeout_seconds = 30",
    ]
    for channel, peer in channels.items():
        lines += [
            "",
            f"[adaptors.{channel}]",
            'transport = "streamable-http"',
            f'url = "http://localhost:{_var(peer, "PORT")}/mcp"',
        ]
    _home(name).mkdir(parents=True, exist_ok=True)
    conf.write_text("\n".join(lines) + "\n")


# MCP client integrations — `gnosislab setup <tool>` merges the five
# server entries into the tool's config file. Each tool: config
# path, the top-level key holding servers, and the entry style —
#   "http"     → {"url": …, "transport": "http"}   (mcpServers schema)
#   "vscode"   → {"type": "http", "url": …}        (VS Code mcp.json)
#   "remote"   → {"type": "remote", "url": …, "enabled": true} (opencode)
MCP_TOOLS = {
    "opencode":    ("~/.config/opencode/opencode.json", "mcp", "remote"),
    "vscodium":    ("~/.config/VSCodium/User/mcp.json", "servers", "vscode"),
    "vscode":      ("~/.config/Code/User/mcp.json", "servers", "vscode"),
    "windsurf":    ("~/.codeium/windsurf/mcp_config.json", "mcpServers", "http"),
    "cursor":      ("~/.cursor/mcp.json", "mcpServers", "http"),
    "claude-code": ("~/.claude.json", "mcpServers", "http"),
    "devin":       ("~/.config/devin/mcp_config.json", "mcpServers", "http"),
}

# Every container key any tool uses — `setup` sweeps our ml-*
# entries out of the wrong ones so a schema fix never leaves stale
# blocks behind.
_MCP_CONTAINER_KEYS = {"mcpServers", "servers", "mcp"}


def _server_entries(style: str) -> dict[str, dict]:
    """{ml-episteme: {…entry in this tool's schema…}, …} from ports."""
    out = {}
    for name in COMPONENTS:
        url = f"http://localhost:{_var(name, 'PORT')}/mcp"
        if style == "vscode":
            entry = {"type": "http", "url": url}
        elif style == "remote":
            entry = {"type": "remote", "url": url, "enabled": True}
        else:
            entry = {"url": url, "transport": "http"}
        out[f"ml-{name}"] = entry
    return out


def _setup(argv: list[str]) -> int:
    tools = [a for a in argv if a in MCP_TOOLS]
    only = None
    dry = False
    for a in argv:
        if a == "--list":
            for t, (path, key, _k) in MCP_TOOLS.items():
                print(f"  {t:<12} {path}  ({key})")
            return 0
        if a == "--print":
            print(json.dumps({"mcpServers": _server_entries("http")},
                             indent=2))
            return 0
        if a == "--dry-run":
            dry = True
        elif a.startswith("--only="):
            only = {s.strip() for s in a[7:].split(",") if s.strip()}
        elif a.startswith("-") and a not in tools:
            print(f"gnosislab setup: unknown option '{a}'", file=sys.stderr)
            return 2
    if not tools:
        print("gnosislab setup <tool> [--only ml-episteme,…] [--dry-run]",
              file=sys.stderr)
        print(f"tools: {', '.join(MCP_TOOLS)}  (or --list)", file=sys.stderr)
        return 2

    for tool in tools:
        path_s, key, style = MCP_TOOLS[tool]
        path = Path(path_s).expanduser()
        merged_entries = _server_entries(style)
        if only:
            merged_entries = {k: v for k, v in merged_entries.items()
                              if k in only}

        # Merge into existing JSON; a malformed file gets backed up,
        # never silently overwritten.
        cfg: dict = {}
        if path.is_file():
            try:
                cfg = json.loads(path.read_text())
                if not isinstance(cfg, dict):
                    raise ValueError("not an object")
            except (ValueError, OSError) as e:
                bak = path.with_suffix(path.suffix + ".bak")
                bak.write_bytes(path.read_bytes())
                print(f"{tool}: existing {path} unreadable ({e})"
                      f" — backed up to {bak}, starting fresh")
                cfg = {}
        cfg.setdefault(key, {}).update(merged_entries)
        # Sweep our ml-* entries out of other container keys (stale
        # blocks from an older schema), dropping keys left empty.
        for other in _MCP_CONTAINER_KEYS - {key}:
            block = cfg.get(other)
            if isinstance(block, dict):
                for k in merged_entries:
                    block.pop(k, None)
                if not block:
                    cfg.pop(other)

        if dry:
            print(f"--- {tool}: {path} (would write) ---")
            print(json.dumps(cfg, indent=2))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        bak = path.with_suffix(path.suffix + ".bak")
        if path.is_file():
            bak.write_bytes(path.read_bytes())
        path.write_text(json.dumps(cfg, indent=2) + "\n")
        names = ", ".join(merged_entries)
        print(f"{tool}: wrote {len(merged_entries)} server"
              f"{'s' if len(merged_entries) > 1 else ''}"
              f" ({names}) -> {path}")
    return 0


def _env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE / export KEY=VALUE lines; # comments, blanks."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        out[key.strip()] = val.strip().strip('"').strip("'")
    return out


def _resolved_env() -> dict[str, str]:
    """defaults < user ports.env < process env — the full ML_* set."""
    env: dict[str, str] = {}
    for name, port in DEFAULT_PORTS.items():
        stem = f"ML_{name.upper()}"
        env[f"{stem}_PORT"] = str(port)
        env[f"{stem}_GUI_PORT"] = str(port + 1)
    # NB: no default for ML_EPISTEME_INGEST_PORT — the server fails
    # closed if a port is set without a token, so it only comes from
    # the user's config/env alongside ML_EPISTEME_INGEST_TOKEN.
    env.update(_env_file(USER_CONFIG))
    for key, val in os.environ.items():
        if key.startswith("ML_"):
            env[key] = val
    # Derived GUI URLs — same rule as ports.env: settable, defaulting
    # to localhost on the resolved GUI port.
    for name in COMPONENTS:
        stem = f"ML_{name.upper()}"
        env[f"{stem}_GUI_URL"] = os.environ.get(
            f"{stem}_GUI_URL",
            env.get(f"{stem}_GUI_URL")
            or f"http://localhost:{env[f'{stem}_GUI_PORT']}",
        )
    return env


def _var(name: str, suffix: str) -> str:
    return _resolved_env()[f"ML_{name.upper()}_{suffix}"]


def _home(name: str) -> Path:
    return Path.home() / f".ml-{name}"


def _pidfile(name: str) -> Path:
    return _home(name) / "run" / "labloop.pid"


def _pid_alive(pid: int | None) -> bool:
    """Liveness probe that does NOT kill the process it probes.

    os.kill(pid, 0) is POSIX-only as a probe: on Windows, os.kill maps
    to TerminateProcess(handle, sig) for any non-console-event sig —
    os.kill(pid, 0) unconditionally TERMINATES the process with exit
    code 0. Using it here would make `start` kill its own child on the
    first health-miss and `status` kill every managed server it checks.
    """
    if not pid:
        return False
    if os.name == "nt":
        import ctypes
        import ctypes.wintypes

        k32 = ctypes.windll.kernel32
        PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
        STILL_ACTIVE = 259
        handle = k32.OpenProcess(
            PROCESS_QUERY_LIMITED_INFORMATION, False, pid
        )
        if not handle:
            return False
        try:
            code = ctypes.wintypes.DWORD()
            if not k32.GetExitCodeProcess(
                handle, ctypes.byref(code)
            ):
                return False
            return code.value == STILL_ACTIVE
        finally:
            k32.CloseHandle(handle)
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def _managed_pid(name: str) -> int | None:
    try:
        return int(_pidfile(name).read_text().strip())
    except (OSError, ValueError):
        return None


def _port_pid(port: int) -> int | None:
    """Listener pid on a TCP port, or None. Same-user processes only."""
    if os.name == "nt":
        # Windows has no ss; netstat -ano prints the owning pid as the
        # last column of each LISTENING row.
        try:
            out = subprocess.run(
                ["netstat", "-ano", "-p", "tcp"],
                capture_output=True, text=True,
            ).stdout
        except OSError:
            return None
        suffix = f":{port}"
        for line in out.splitlines():
            parts = line.split()
            if len(parts) >= 5 and parts[3] == "LISTENING" \
                    and parts[1].endswith(suffix):
                try:
                    return int(parts[-1])
                except ValueError:
                    continue
        return None
    try:
        out = subprocess.run(
            ["ss", "-ltnpH", f"sport = :{port}"],
            capture_output=True, text=True,
        ).stdout
    except OSError:
        return None
    for part in out.split("pid=")[1:]:
        try:
            return int(part.split(",")[0].rstrip(")"))
        except ValueError:
            continue
    return None


# Health/status probes go to 127.0.0.1 only — never through a system
# proxy. urllib honours proxy env vars and, on Windows, the registry
# (WPAD auto-detection can stall a urlopen for seconds). Localhost
# traffic must not traverse that path or health checks look hung.
_LOCAL = urllib.request.build_opener(urllib.request.ProxyHandler({}))


def _is_up(name: str) -> bool:
    try:
        _LOCAL.open(
            f"http://127.0.0.1:{_var(name, 'PORT')}/health", timeout=2
        )
        return True
    except OSError:
        return False


def _child_env() -> dict[str, str]:
    env = dict(os.environ)
    env.update(_resolved_env())
    return env


def start_one(name: str) -> int:
    mcp = int(_var(name, "PORT"))
    gui = int(_var(name, "GUI_PORT"))
    pid = _managed_pid(name)
    if _pid_alive(pid):
        print(f"{name}: already running (pid {pid})")
        return 0
    existing = _port_pid(mcp)
    if existing:
        print(f"{name}: already running (pid {existing}, unmanaged"
              " — not started via gnosislab)")
        return 0

    home = _home(name)
    (home / "run").mkdir(parents=True, exist_ok=True)
    (home / "logs").mkdir(parents=True, exist_ok=True)
    _ensure_server_config(name)
    log = home / "logs" / "server.log"

    args = [
        sys.executable, "-m", f"ml_{name}_mcp",
        "--transport", "http",
        "--port", str(mcp),
        "--stateless",
        "--observability-port", str(gui),
    ]
    # Ingest is enabled iff a token is configured (fail closed,
    # same as run-ml-episteme.sh).
    env = _child_env()
    if env.get("ML_EPISTEME_INGEST_PORT") and \
            env.get("ML_EPISTEME_INGEST_TOKEN") and name == "episteme":
        args += ["--ingest-port", env["ML_EPISTEME_INGEST_PORT"]]

    log_fh = open(log, "a")
    proc = subprocess.Popen(
        args, env=env, stdin=subprocess.DEVNULL,
        stdout=log_fh, stderr=subprocess.STDOUT,
        start_new_session=True,  # setsid — own process group
    )
    log_fh.close()
    _pidfile(name).write_text(f"{proc.pid}\n")

    # Wait for /health so `start all` brings upstreams up cleanly
    # before their consumers — keeps the integrity trail clean.
    for _ in range(80):
        if _is_up(name):
            print(f"{name}: up (pid {proc.pid}, mcp :{mcp}, gui :{gui})")
            return 0
        if not _pid_alive(proc.pid):
            print(f"{name}: died on startup — see {log}", file=sys.stderr)
            _pidfile(name).unlink(missing_ok=True)
            return 1
        time.sleep(0.5)
    print(f"{name}: still starting (pid {proc.pid}) — see {log}")
    return 0


def _kill_group_or_proc(pid: int, sig) -> None:
    """killpg the child's group (POSIX) or kill the process itself.

    Windows has neither os.killpg nor SIGKILL — os.kill maps to
    TerminateProcess, and process trees there are out of scope for
    group semantics (spawned grandchildren need taskkill /T, which we
    deliberately don't reach for).
    """
    killpg = getattr(os, "killpg", None)
    if killpg is not None:
        try:
            killpg(pid, sig)
            return
        except OSError:
            pass
    try:
        os.kill(pid, sig)
    except OSError:
        pass


def stop_one(name: str) -> int:
    pid = _managed_pid(name)
    if _pid_alive(pid):
        # start_new_session made the child its own process-group
        # leader — kill the group so any children go down with it.
        _kill_group_or_proc(pid, signal.SIGTERM)
    else:
        lpid = _port_pid(int(_var(name, "PORT")))
        if lpid is None:
            print(f"{name}: not running")
            _pidfile(name).unlink(missing_ok=True)
            return 0
        print(f"{name}: running unmanaged (pid {lpid})"
              " — terminating by port")
        try:
            os.kill(lpid, signal.SIGTERM)
        except OSError:
            pass
        pid = lpid

    for _ in range(40):
        if not _pid_alive(pid):
            break
        time.sleep(0.5)
    if _pid_alive(pid):
        _kill_group_or_proc(pid, getattr(signal, "SIGKILL", signal.SIGTERM))
    _pidfile(name).unlink(missing_ok=True)
    print(f"{name}: stopped")
    return 0


def status_one(name: str) -> None:
    pid = _managed_pid(name)
    if _pid_alive(pid):
        state = f"up (pid {pid}, managed)"
    else:
        lpid = _port_pid(int(_var(name, "PORT")))
        state = f"up (pid {lpid}, unmanaged)" if lpid else "down"
    health = "health ok" if _is_up(name) else "-"
    print(f"{name:<10} {state:<26} mcp :{_var(name, 'PORT'):<5} "
          f"gui :{_var(name, 'GUI_PORT'):<5} {health}")


def _resolve(target: str) -> list[str]:
    if target == "all":
        return list(COMPONENTS)
    if target in COMPONENTS:
        return [target]
    print(f"gnosislab: unknown component '{target}'", file=sys.stderr)
    print(f"expected: {' '.join(COMPONENTS)} | all", file=sys.stderr)
    sys.exit(2)


def _dashboard(name: str) -> int:
    """Open a server's observability GUI in a browser.

    The URL is ML_<NAME>_GUI_URL from the resolved env (defaults <
    ~/.config/gnosislab/ports.env < process env) — remote/VM users
    point it at their gateway; locally it is http://localhost:<gui>.
    """
    import webbrowser

    url = _var(name, "GUI_URL")
    if webbrowser.open(url):
        print(f"{name}: opened {url}")
    else:
        print(f"{name}: {url}  (no browser found — open manually)")
    return 0


def _logs(name: str) -> int:
    log = _home(name) / "logs" / "server.log"
    if not log.is_file():
        print(f"gnosislab: no log at {log}", file=sys.stderr)
        return 1
    with open(log) as fh:
        lines = fh.readlines()
        sys.stdout.writelines(lines[-10:])
        sys.stdout.flush()
        try:
            while True:
                line = fh.readline()
                if line:
                    sys.stdout.write(line)
                    sys.stdout.flush()
                else:
                    time.sleep(0.25)
        except KeyboardInterrupt:
            return 0


def _config() -> int:
    print(f"config file: {USER_CONFIG}"
          f" ({'present' if USER_CONFIG.is_file() else 'absent — using defaults'})")
    env = _resolved_env()
    for name in COMPONENTS:
        stem = f"ML_{name.upper()}"
        cfg = _server_config_source(name)
        cfg_s = str(cfg) if cfg else (
            "generated ~/.ml-%s/config.toml on start"
            % name if PEER_CHANNELS.get(name) else "defaults")
        print(f"  {stem}_PORT={env[stem + '_PORT']}  "
              f"{stem}_GUI_PORT={env[stem + '_GUI_PORT']}   "
              f"config: {cfg_s}")
    print("env overrides: any ML_* variable set in the environment wins")
    return 0


def _export(argv: list[str]) -> int:
    """Package a diagnostic run, or export provenance.

    Default (tarball): diagnostics/out/<slug>/ + per-server health,
    log tails and integrity checks → sxport/<UTC>-<slug>.tar.gz.
    --format ro-crate|… delegates to the gnosislab_export package,
    which reads the stores read-only.
    """
    fmt, zip_flag, slug, full = "tarball", False, None, False
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--format" and i + 1 < len(argv):
            fmt = argv[i + 1]
            i += 2
        elif a == "--zip":
            zip_flag = True
            i += 1
        elif a == "--full":
            full = True
            i += 1
        elif a.startswith("-"):
            print(f"gnosislab export: unknown flag '{a}'",
                  file=sys.stderr)
            return 2
        elif slug is None:
            slug = a
            i += 1
        else:
            print(f"gnosislab export: unexpected arg '{a}'",
                  file=sys.stderr)
            return 2
    if full and slug:
        print("gnosislab export: --full takes no slug", file=sys.stderr)
        return 2
    if not slug and not full:
        print("gnosislab export: missing slug — expected "
              "'gnosislab export <slug>' (or --full --format …)",
              file=sys.stderr)
        return 2

    if full and fmt == "tarball":
        print("gnosislab export: --full applies to provenance formats — "
              "use '--full --format ro-crate'", file=sys.stderr)
        return 2
    if fmt != "tarball":
        from gnosislab_export.cli import main as export_main
        if full:
            args = ["--full", "--format", fmt,
                    "--out", "sxport/full-rocrate"]
        else:
            args = ["--programme", slug, "--format", fmt,
                    "--out", f"sxport/{slug}-rocrate"]
        if zip_flag:
            args.append("--zip")
        return export_main(args)

    if slug == "all" or "/" in slug or ".." in slug:
        print(f"gnosislab export: bad slug '{slug}' — use a simple name "
              "(e.g. the diagnostics filename without .md)",
              file=sys.stderr)
        return 2

    import contextlib
    import hashlib
    import io
    import shutil
    import socket
    import tarfile
    from datetime import datetime, timezone

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%MZ")
    Path("sxport").mkdir(exist_ok=True)
    stage = Path("sxport") / f"{stamp}-{slug}"
    out = Path(f"{stage}.tar.gz")
    shutil.rmtree(stage, ignore_errors=True)
    stage.mkdir(parents=True)

    # Agent payload — required; a diagnostic that produced nothing
    # exports nothing.
    payload_src = Path("diagnostics") / "out" / slug
    if payload_src.is_dir():
        shutil.copytree(payload_src, stage / "payload")
    else:
        print(f"gnosislab export: warning — {payload_src} not found; "
              "exporting server state only", file=sys.stderr)
        (stage / "payload").mkdir()

    # Per-server health snapshots + log tails + integrity check logs.
    (stage / "health").mkdir()
    (stage / "logs").mkdir()
    (stage / "integrity").mkdir()
    for name in COMPONENTS:
        for tag, port_key, url_path in (
            ("mcp-health", "PORT", "health"),
            ("gui-deep", "GUI_PORT", "health/deep"),
        ):
            dest = stage / "health" / f"{name}-{tag}.json"
            try:
                with _LOCAL.open(
                    f"http://127.0.0.1:{_var(name, port_key)}/{url_path}",
                    timeout=3,
                ) as r:
                    dest.write_bytes(r.read())
            except Exception:
                dest.write_text('{"error":"unreachable"}')
        log = _home(name) / "logs" / "server.log"
        if log.is_file():
            lines = log.read_text(errors="replace").splitlines(
                keepends=True)
            (stage / "logs" / f"{name}.log").write_text(
                "".join(lines[-1000:]))
        for f in sorted((_home(name) / "logs").glob("check-*.jsonl")):
            shutil.copy2(f, stage / "integrity" / f"{name}-{f.name}")

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        for name in COMPONENTS:
            status_one(name)
    manifest = (
        f"slug: {slug}\n"
        f"exported_at: {datetime.now(timezone.utc):%Y-%m-%dT%H:%M:%SZ}\n"
        f"host: {socket.getfqdn()}\n"
        "labloop_status:\n" + buf.getvalue()
    )
    (stage / "MANIFEST.txt").write_text(manifest)

    with tarfile.open(out, "w:gz") as tar:
        tar.add(stage, arcname=stage.name)
    shutil.rmtree(stage)
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    print(f"{digest}  {out}")
    print(f"bytes: {out.stat().st_size}")
    print(f"export: {out}")
    return 0


def _version() -> int:
    from importlib.metadata import PackageNotFoundError, version
    try:
        print(f"gnosislab {version('gnosislab')}")
    except PackageNotFoundError:
        print("gnosislab (uninstalled source tree)")
    return 0


def _upgrade() -> int:
    """Upgrade the CLI itself to the latest release.

    Delegates to whichever installer owns this installation:
      uv tool          → uv tool upgrade gnosislab
      pipx             → pipx upgrade gnosislab
      editable/source  → git pull --rebase && uv sync — in a checkout
                         PyPI is downstream of the tree, not upstream
      pip venv         → python -m pip install -U gnosislab
      uv venv          → uv pip install --python <exe> -U gnosislab
                         (uv venvs ship no pip module by design)
    """
    import importlib.util
    import shutil
    from importlib.metadata import distribution

    editable = False
    try:
        direct = json.loads(
            distribution("gnosislab").read_text("direct_url.json")
            or "{}")
        editable = bool(direct.get("dir_info", {}).get("editable"))
    except Exception:
        pass

    if "uv/tools" in sys.prefix or "uv\\tools" in sys.prefix:
        steps = [["uv", "tool", "upgrade", "gnosislab"]]
    elif "pipx" in sys.prefix:
        steps = [["pipx", "upgrade", "gnosislab"]]
    elif editable:
        print("gnosislab: source checkout — upgrading means pulling "
              "git, not installing from PyPI")
        steps = [["git", "pull", "--rebase"], ["uv", "sync"]]
    elif importlib.util.find_spec("pip") is not None:
        steps = [[sys.executable, "-m", "pip", "install", "-U",
                  "gnosislab"]]
    elif shutil.which("uv"):
        steps = [["uv", "pip", "install", "--python", sys.executable,
                  "-U", "gnosislab"]]
    else:
        print("gnosislab: can't self-upgrade — no pip module in this "
              "environment and no uv on PATH; reinstall with "
              "`uv tool install gnosislab` or `pip install gnosislab`",
              file=sys.stderr)
        return 1

    if os.name == "nt":
        # Windows locks a running exe: gnosislab.exe can't be replaced
        # while this very process holds it (uv fails with error 32 —
        # file in use). Hand the upgrade to a detached helper that
        # waits for this PID to exit, then runs the steps.
        import tempfile

        pid = os.getpid()
        lines = [
            "@echo off",
            ":wait",
            f'tasklist /fi "PID eq {pid}" | find "{pid}" >nul 2>&1',
            "if %errorlevel%==0 (",
            "  timeout /t 1 /nobreak >nul",
            "  goto wait",
            ")",
        ]
        for cmd in steps:
            lines.append(subprocess.list2cmdline(cmd))
            lines += [
                "if %errorlevel% neq 0 (",
                "  echo gnosislab: upgrade FAILED",
                "  pause",
                "  exit /b %errorlevel%",
                ")",
            ]
        lines += [
            "echo gnosislab: upgrade complete",
            "gnosislab version",
            "pause",
            'del "%~f0"',
        ]
        script = Path(tempfile.gettempdir()) / f"gnosislab-upgrade-{pid}.cmd"
        script.write_text("\r\n".join(lines) + "\r\n")
        # CREATE_NEW_CONSOLE: the helper gets its own window and
        # outlives this process; detaching silently would hide the
        # upgrade's progress and its failure.
        subprocess.Popen(
            ["cmd", "/c", str(script)],
            creationflags=subprocess.CREATE_NEW_CONSOLE,
            close_fds=True,
        )
        print("gnosislab: updater spawned in a new window — it runs"
              " the moment this process exits")
        return 0

    for cmd in steps:
        print(f"gnosislab: {' '.join(cmd)}")
        rc = subprocess.run(cmd).returncode
        if rc != 0:
            return rc
    _version()
    return 0


USAGE = """gnosislab — lifecycle for the ml-* loop stack.
(`labloop` is a transition alias to this command — same thing.)

  gnosislab start   [name|all]   background a server (upstreams first on all)
  gnosislab stop    [name|all]   terminate (consumers first on all)
  gnosislab restart [name|all]
  gnosislab status  [name|all]   pid/ports/health per server (default: all)
  gnosislab logs    <name>       follow ~/.ml-<name>/logs/server.log
  gnosislab dashboard [name]     open the server's GUI in a browser
                                 (default: agora — the lab status hub)
  gnosislab config               show resolved ports + config file path
  gnosislab version              print the installed CLI version
  gnosislab upgrade              upgrade the CLI itself — uv tool / pipx /
                                 pip, or git pull in a source checkout
  gnosislab setup   <tool>       merge the five servers into a client's
                                 MCP config (opencode, vscodium, vscode,
                                 windsurf, cursor, claude-code, devin);
                                 --list, --print, --dry-run, --only=…
  gnosislab export  <slug>       package diagnostics/out/<slug>/ + server
                                 health/logs/integrity trail into
                                 sxport/<UTC>-<slug>.tar.gz (prints path
                                 + sha256 — report these in the run log)
  gnosislab export  <slug> --format ro-crate|prov|jsonld [--zip]
                                 export the programme's provenance
                                 (read-only; payload/ + format metadata:
                                 ro-crate-metadata.json, prov.json, or
                                 export.jsonld)
  gnosislab export  --full --format ro-crate|prov|jsonld [--zip]
                                 export the whole store's provenance

names: anamnesis  episteme  zetesis  arete  agora

status shows each server as:
  managed    — started via `gnosislab start`; tracked by pidfile
               (~/.ml-<name>/run/labloop.pid), logs to
               ~/.ml-<name>/logs/server.log, full lifecycle control.
  unmanaged  — running but not started via gnosislab (e.g. run-ml-*.sh
               in a terminal); detected by port probe. `stop` still
               terminates it by resolving the listener pid, but its
               stdout lives wherever it was launched and it leaves
               no labloop log.

ports: defaults < ~/.config/gnosislab/ports.env < environment.
The file uses the same KEY=VALUE format as the repo's ports.env;
runtime state lives in ~/.ml-<name>/ regardless of install method.
"""


def main() -> None:
    if Path(sys.argv[0]).name == "labloop":
        print("note: 'labloop' is being renamed to 'gnosislab'"
              " — this alias will be removed after the transition",
              file=sys.stderr)
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    target = sys.argv[2] if len(sys.argv) > 2 else "all"

    if cmd in ("-h", "--help", "help"):
        print(USAGE)
        sys.exit(0)
    if cmd in ("-V", "--version", "version"):
        sys.exit(_version())
    if cmd == "upgrade":
        sys.exit(_upgrade())
    if cmd in ("start", "stop", "status"):
        rc = 0
        for n in _resolve(target):
            rc |= {"start": start_one, "stop": stop_one,
                   "status": status_one}[cmd](n) or 0
        sys.exit(rc)
    if cmd == "restart":
        for n in reversed(_resolve(target)):
            stop_one(n)
        rc = 0
        for n in _resolve(target):
            rc |= start_one(n) or 0
        sys.exit(rc)
    if cmd == "logs":
        if target == "all":
            print(USAGE, file=sys.stderr)
            sys.exit(2)
        _resolve(target)
        sys.exit(_logs(target))
    if cmd in ("dashboard", "gui"):
        if target == "all":
            target = "agora"
        _resolve(target)
        sys.exit(_dashboard(target))
    if cmd == "config":
        sys.exit(_config())
    if cmd == "setup":
        sys.exit(_setup(sys.argv[2:]))
    if cmd == "export":
        sys.exit(_export(sys.argv[2:]))

    print(USAGE)
    sys.exit(2 if cmd else 0)


if __name__ == "__main__":
    main()
