#!/usr/bin/env bash
# bump-version.sh — bump the distribution version, regenerate the
# umbrella pyproject, commit, and tag.
#
#   scripts/bump-version.sh            # patch bump (0.1.15 → 0.1.16)
#   scripts/bump-version.sh minor      # 0.1.15 → 0.2.0
#   scripts/bump-version.sh major      # 0.1.15 → 1.0.0
#   scripts/bump-version.sh 0.3.0      # explicit version
#   scripts/bump-version.sh --no-git   # bump + regenerate only, no commit/tag
#
# The canonical version lives in ml-scientist/pyproject.toml; the root
# pyproject.toml is GENERATED from it (same pipeline as the source
# repo's export-gnosislab.sh). Order is bump → regenerate → commit →
# tag so a v<ver> tag can never point at a tree whose pyproject
# disagrees (the publish script refuses on mismatch anyway).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUB_PYPROJECT="$ROOT/ml-scientist/pyproject.toml"
ROOT_PYPROJECT="$ROOT/pyproject.toml"

GIT=1
KIND="patch"
for arg in "$@"; do
  case "$arg" in
    --no-git) GIT=0 ;;
    patch|minor|major) KIND="$arg" ;;
    [0-9]*.[0-9]*.[0-9]*) KIND="explicit"; NEW="$arg" ;;
    -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
    *) echo "bump: unknown option '$arg' (try --help)" >&2; exit 2 ;;
  esac
done

# ── compute new version ───────────────────────────────────────────
CUR="$(sed -n 's/^version = "\(.*\)"$/\1/p' "$SUB_PYPROJECT" | head -1)"
[ -n "$CUR" ] || {
  echo "bump: can't read version from $SUB_PYPROJECT" >&2; exit 1; }

if [ "$KIND" != "explicit" ]; then
  IFS=. read -r major minor patch <<< "$CUR"
  case "$KIND" in
    patch) NEW="$major.$minor.$((patch + 1))" ;;
    minor) NEW="$major.$((minor + 1)).0" ;;
    major) NEW="$((major + 1)).0.0" ;;
  esac
fi

if git -C "$ROOT" rev-parse -q --verify "refs/tags/v$NEW" >/dev/null 2>&1; then
  echo "bump: tag v$NEW already exists in $ROOT" >&2; exit 1
fi

# ── bump subsystem pyproject → regenerate umbrella ────────────────
sed -i "0,/^version = \"$CUR\"$/s//version = \"$NEW\"/" "$SUB_PYPROJECT"
# Keep the lockfile's recorded project version in step — a stale
# [[package]] block trips 'uv sync --locked' and reads wrongly.
(cd "$ROOT/ml-scientist" && uv lock --quiet)

# Root pyproject is GENERATED from the subsystem's: same metadata,
# deps, scripts and test config; name and paths repointed — the same
# pipeline the source repo's export-gnosislab.sh runs, kept inline so
# the umbrella can regenerate itself.
{
  echo '# GENERATED by export-gnosislab.sh — edit ml-scientist/pyproject.toml'
  sed \
    -e 's/^name = "[^"]*"$/name = "gnosislab"/' \
    -e 's/^authors = .*/authors = [{ name = "Alexander Bikeyev", email = "alex.bikeyev@pm.me" }]/' \
    -e 's|"src/|"ml-scientist/src/|g' \
    -e 's|^testpaths = \["tests"\]$|testpaths = ["ml-scientist/tests"]|' \
    "$SUB_PYPROJECT"
} > "$ROOT_PYPROJECT"
(cd "$ROOT" && uv lock --quiet)

grep -q "^version = \"$NEW\"$" "$ROOT_PYPROJECT" || {
  echo "bump: umbrella pyproject did not pick up $NEW" >&2; exit 1; }
grep -q '^name = "gnosislab"$' "$ROOT_PYPROJECT" || {
  echo "bump: umbrella pyproject generation failed" >&2; exit 1; }

# ── commit + tag ──────────────────────────────────────────────────
if [ "$GIT" -eq 1 ]; then
  git -C "$ROOT" add -A
  git -C "$ROOT" commit -qm "gnosislab $NEW"
  git -C "$ROOT" push -q origin HEAD
  git -C "$ROOT" tag "v$NEW"
  git -C "$ROOT" push -q origin "v$NEW"
  echo "bump: committed + tagged v$NEW and pushed to origin"
fi

cat <<EOF
bump: $CUR -> $NEW
next: $ROOT/scripts/publish-gnosislab.sh --ref v$NEW
EOF
